# PORT - 9191
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: order-service
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  strategy: {}
  template:
    metadata:

      labels:
        app: order-service
    spec:
      containers:
        - env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-order:5432/order_service
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          image: kenferns93/order-service:latest
          name: order-service
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: order-service
  name: order-service
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 9191
  selector:
    app: order-service
status:
  loadBalancer: {}